[project]
name = "app-python"
version = "0.1.0"
description = ""
authors = [
    {name = "dmhd6219",email = "svyatoslavsvyatkin@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard] (>=0.115.7,<0.116.0)",
    "pre-commit (>=4.1.0,<5.0.0)",
    "mypy (>=1.14.1,<2.0.0)",
    "pylint (>=3.3.3,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
